#!/bin/bash

sed -i s/2.*.*/2.2.1/ ./*/*/*/*/*/*
#sed -i s/2.3.x/2.2.1/ ./*/*/*/*/*/*
sed -i s/paraFoam// ./*/*/*/*/*/*
sed -i s/2.*.*/2.2.1/ ./*/*/*/*/*
#sed -i s/2.3.x/2.2.1/ ./*/*/*/*/*
sed -i s/paraFoam// ./*/*/*/*/*
sed -i s/2.*.*/2.2.1/ ./*/*/*/*
#sed -i s/2.3.x/2.2.1/ ./*/*/*/*
sed -i s/paraFoam// ./*/*/*/*
sed -i s/2.*.*/2.2.1/ ./*/*/*
#sed -i s/2.3.x/2.2.1/ ./*/*/*
sed -i s/paraFoam// ./*/*/*
sed -i s/2.*.*/2.2.1/ ./*/*
#sed -i s/2.3.x/2.2.1/ ./*/*
sed -i s/paraFoam// ./*/*
#sed -i s/2.3.0/2.2.1/ ./*
#sed -i s/2.3.x/2.2.1/ ./*
#sed -i s/paraFoam// ./*
#sed -i s/2.2.1/2.2.1/ *
#sed -i s/2.2.1/2.2.1/ *
#sed -i s/// *
